FROM dataquadrant/sagemaker-notebook-2024:python2

# ==================================================================
# Create environment(s)
# ------------------------------------------------------------------

USER $NB_UID

RUN $HOME/envs/create_env_file.sh tensorflow_p27 && \
    $HOME/envs/create_env.sh tensorflow_p27